apps/noticias/urls.py
from django.urls import path 
from . import views

app_name ='noticias'

urlpatterns = [
    path ('',views.Home_Noticias, name="h_noticias"),
]

proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.Home, name ='inicio'),
    path('Contacto', views.Contacto, name = 'contacto'),


#APP NOTICIAS

    path('noticias/', include('apps.noticias.urls')),
]

apps/noticias/models.py
from django.db import models

# Create your models here.

apps/noticias/views.py
from django.shortcuts import render

# Create your views here.

def Home_Noticias(request):

    return render(request, 'noticias/home_noticias.html')

proyecto/views.py
from django.shortcuts import render

def Home(request):

	return render(request,'home.html')

def Contacto(request):
	
    return render(request,'contacto.html')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>INFORMATORIO</title>
	<link rel="stylesheet" type="text/css" href="{% static  'css/main.css' %}">
</head>
<body>
	<h1 class="titulo">MENU</h1>
	<img src="{% static 'img/gatito.png' %}" width="150px">
    <ul>
		<li><a href="{% url 'inicio' %}">Home</a></li>
		<li><a href="{% url 'contacto' %}">Contacto</a>
		</li>
        <li><a href="{% url 'noticias:h_noticias' %}">NOTICIAS</a></li>
    </ul>


    {% block contenido %}

    {% endblock contenido %}

</body>
</html>

templates/contacto.html
{% extends 'base.html' %}


{% block contenido %}
    <h1>SOY EL CONTACTO</h1>
{% endblock contenido %}	

templates/home.html
{% extends 'base.html' %}


{% block contenido %}
    <h1>SOY EL HOME</h1> 
{% endblock contenido %}	

templates/noticias/home_noticias.html
{% extends 'base.html' %}


{% block contenido %}
    <h1>SOY HOME DE NOTICIAS</h1> 
{% endblock contenido %}	